#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

INFRA:
  - ".github/**/*"
  - "appveyor.yml"
  - "tools/**/*"
  - "dev/create-release/**/*"
  - ".asf.yaml"
  - ".gitattributes"
  - ".gitignore"
  - "dev/merge_spark_pr.py"
  - "dev/run-tests-jenkins*"
BUILD:
 - any: ['dev/**/*', '!dev/merge_spark_pr.py', '!dev/run-tests-jenkins*']
 - "build/**/*"
 - "project/**/*"
 - "assembly/**/*"
 - "**/*pom.xml"
 - "bin/docker-image-tool.sh"
 - "bin/find-spark-home*"
 - "scalastyle-config.xml"
DOCS:
  - "docs/**/*"
  - "**/README.md"
  - "**/CONTRIBUTING.md"
  - "python/docs/**/*"
EXAMPLES:
  - "examples/**/*"
  - "bin/run-example*"
CORE:
  - any: ["core/**/*", "!**/*UI.scala", "!**/ui/**/*"]
  - "common/kvstore/**/*"
  - "common/network-common/**/*"
  - "common/network-shuffle/**/*"
  - "python/pyspark/*.py"
  - "python/pyspark/tests/**/*.py"
SPARK SUBMIT:
  - "bin/spark-submit*"
SPARK SHELL:
  - "repl/**/*"
  - "bin/spark-shell*"
SQL:
  - any: ["**/sql/**/*", "!python/pyspark/sql/avro/**/*", "!python/pyspark/sql/streaming/**/*", "!python/pyspark/sql/tests/streaming/test_streaming*.py"]
  - "common/unsafe/**/*"
  - "bin/spark-sql*"
  - "bin/beeline*"
  - "sbin/*thriftserver*.sh"
  - "**/*SQL*.R"
  - "**/DataFrame.R"
  - "**/*WindowSpec.R"
  - "**/*catalog.R"
  - "**/*column.R"
  - "**/*functions.R"
  - "**/*group.R"
  - "**/*schema.R"
  - "**/*types.R"
AVRO:
  - "connector/avro/**/*"
  - "python/pyspark/sql/avro/**/*"
DSTREAM:
  - "streaming/**/*"
  - "data/streaming/**/*"
  - "connector/kinesis*"
  - "connector/kafka*"
  - "python/pyspark/streaming/**/*"
GRAPHX:
  - "graphx/**/*"
  - "data/graphx/**/*"
ML:
  - "**/ml/**/*"
  - "**/*mllib_*.R"
MLLIB:
  - "**/spark/mllib/**/*"
  - "mllib-local/**/*"
  - "python/pyspark/mllib/**/*"
STRUCTURED STREAMING:
  - "**/sql/**/streaming/**/*"
  - "connector/kafka-0-10-sql/**/*"
  - "python/pyspark/sql/streaming/**/*"
  - "python/pyspark/sql/tests/streaming/test_streaming*.py"
  - "**/*streaming.R"
PYTHON:
  - "bin/pyspark*"
  - "**/python/**/*"
PANDAS API ON SPARK:
  - "python/pyspark/pandas/**/*"
R:
  - "**/r/**/*"
  - "**/R/**/*"
  - "bin/sparkR*"
YARN:
  - "resource-managers/yarn/**/*"
KUBERNETES:
  - "resource-managers/kubernetes/**/*"
WINDOWS:
  - "**/*.cmd"
  - "R/pkg/tests/fulltests/test_Windows.R"
WEB UI:
  - "**/ui/**/*"
  - "**/*UI.scala"
DEPLOY:
  - "sbin/**/*"
CONNECT:
  - "connector/connect/**/*"
  - "python/pyspark/sql/**/connect/**/*"
  - "python/pyspark/ml/**/connect/**/*"
PROTOBUF:
  - "connector/protobuf/**/*"
  - "python/pyspark/sql/protobuf/**/*"
